#include <iostream>
#include <iomanip>
#include <locale>

#include <TROOT.h>
#include <TChain.h>
#include <TFile.h>

#include "vector"
#include "vector"
using std::vector;

#include <TH2.h>
#include <TStyle.h>
#include <TCanvas.h>

TTree          *fChain;   //!pointer to the analyzed TTree or TChain               
Int_t           fCurrent; //!current Tree number in a TChain                       

void HeatMap() {


  // read the Tree generated by tree1w and fill two histograms
  // note that we use "new" to create the TFile and TTree objects,
  // to keep them alive after leaving this function.

  const char* inputfile="Analysis.root";
  const char* hnum="xycrd";
  const char* hdenom="xycr";

  TFile *f = new TFile(inputfile);


  TH2F* nhist = static_cast<TH2F*>(f->Get(hnum)->Clone());
  TH2F* dhist = static_cast<TH2F*>(f->Get(hdenom)->Clone());


  //TH2F* nhistrb = nhist->Rebin2D(10,10);
  //TH2F* dhistrb = dhist->Rebin2D(10,10);
  TH2F* nhistrb = static_cast<TH2F*>(nhist->Clone());
  TH2F* dhistrb = static_cast<TH2F*>(dhist->Clone());
  TH2F* rhist = static_cast<TH2F*>(nhistrb->Clone());




  int nbinxnum = nhistrb->GetNbinsX();
  int nbinynum = nhistrb->GetNbinsY();
  std::cout<<"numerator histogram has "<<nbinxnum<<" bins in x and "<<nbinynum<<
    " bins in y"<<std::endl;

  int nbinxdenom = dhistrb->GetNbinsX();
  int nbinydenom = dhistrb->GetNbinsY();
  std::cout<<"denominator histogram has "<<nbinxdenom<<" bins in x and "<<nbinydenom<<" bins in y"<<std::endl;


  std::cout<<"entries in num "<<std::endl;
  for(int i=0;i<=nbinxnum;i++) {
    for(int j=0;j<nbinynum;j++) {
      std::cout<<" "<<nhistrb->GetBinContent(i,j);
    }
    std::cout<<std::endl;
  }


  std::cout<<"entries in denom "<<std::endl;
  for(int i=0;i<=nbinxdenom;i++) {
    for(int j=0;j<nbinydenom;j++) {
      std::cout<<" "<<dhistrb->GetBinContent(i,j);
    }
    std::cout<<std::endl;
  }



  gStyle->SetOptStat(0);

  TString canvName = "Fig_";
  canvName += "haha";


  int W = 800;
  int H = 600;
  TCanvas* canv = new TCanvas(canvName,canvName,50,50,W,H);
  // references for T, B, L, R                                                  
  float T = 0.08*H;
  float B = 0.12*H;
  float L = 0.12*W;
  float R = 0.04*W;



  canv->SetFillColor(0);
  canv->SetBorderMode(0);
  canv->SetFrameFillStyle(0);
  canv->SetFrameBorderMode(0);
  canv->SetLeftMargin( L/W );
  canv->SetRightMargin( R/W );
  canv->SetTopMargin( T/H );
  canv->SetBottomMargin( B/H );
  canv->SetTickx(0);
  canv->SetTicky(0);
  canv->SetRightMargin(canv->GetLeftMargin());




  // get histogram of events before trigger

    rhist->Divide(dhist);

    rhist->Draw("COLZ");


  std::cout<<"entries in division "<<std::endl;
  for(int i=0;i<=nbinxdenom;i++) {
    for(int j=0;j<nbinydenom;j++) {
      std::cout<<" "<<rhist->GetBinContent(i,j);
    }
    std::cout<<std::endl;
  }




  canv->Update();
  canv->RedrawAxis();
  canv->GetFrame()->Draw();


  return;


}
